services:
  - type: web
    name: asset-management-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist

  - type: web
    name: asset-management-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    healthCheckPath: /health